### ISSUE TITLE
issue: Package manager mismatch + other code issues

### ISSUE THREAD

**Issue by axisiscool** [environment-dev/minio-image-proxy#1]
There's many things wrong with this code:

* The use of yarn and npm
* Express usage, instead of fastify
* Failure to lint prisma schema
* Useless env keys
* Lack of code formatting and basic code practices

Please in the future make use of ESLint to format your code, and pick one package manager, and make use of simple practices such as de-structuring, semicolons, and env validation. This code looks like it's written by 12 year old wannabe programmer.

**Comment by undecla** [comment]
Are you drunk

**Comment by Vetlix** [comment]
I can confirm he is not drunk, but just somewhat sleep-deprived. But everything he has said here is completely true and should be fixed immediately as the code is dogshit.

**Comment by undecla** [comment]
>     * The use of yarn and npm
Nothing wrong with that, you shouldn't experience node_modules inconsistency unless the version is over-written (which isn't possible in npm since at least 2014)

>     * Express usage, instead of fastify
This is pedantic and is all down to programmer preference. You can easily vertically scale express to perform better than fastify.

>     * Failure to lint prisma schema
This is pedantic and yet again all down to code-style.

>     * Useless env keys
If you understand the code enough to be running it on your machine I wouldn't be worried about useless env keys, it's never going to cause an issue. Nor is ".env.example" even "code"

>     * Lack of code formatting and basic code practices
What are "basic code practices?" The code looks perfectly formatted to me.

> Please in the future make use of ESLint to format your code, and pick one package manager, and make use of simple practices such as de-structuring, semicolons, and env validation. This code looks like it's written by 12 year old wannabe programmer.

Automatic semicolon insertion has been part of the ECMAScript spec for [as long as I can remember](https://www-archive.mozilla.org/js/language/E262-3.pdf), it is by no means a reason to use as a complaint for someones code. Numerous of your favorite libraries may lack semicolons, such as [body-parser](https://github.com/expressjs/body-parser), hell, even **[fastify](https://github.com/fastify/fastify)** themselves don't use semicolons in their codebase! 
Environment key validation is useless and honestly a waste of time on something this small. There is an [ESLint config file](https://github.com/environment-dev/minio-image-proxy/blob/master/.eslintrc.js), obviously you must have been too sleep deprived to see it. Lastly I see a use of object destructuring on the very first line of [index.js](https://github.com/environment-dev/minio-image-proxy/blob/master/index.js#L1)!

Obviously you were too "sleep-deprived" to be writing this issue and I think you should take your matters to another place.

**Comment by environment-dev** [comment]
I'm almost certain that if these "issues" where present in aspect's code you would have completely ignored them. I do not see how any of this because a issue, as all of these issues are either super pedantic or are just straight up lies.


Please get a life
~ environment

**Comment by Vetlix** [comment]
> 
> 
> > ```
> > * The use of yarn and npm
> > ```
> 
> Nothing wrong with that, you shouldn't experience node_modules inconsistency unless the version is overwritten (which isn't possible in npm since at least 2014)
> 
If you use both npm and yarn in a project, you will receive this warning:
```prolog
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
```
I don't think it's put there for no reason.
> > ```
> > * Express usage, instead of fastify
> > ```
> 
> This is pedantic and is all down to programmer preference. You can easily vertically scale express to perform better than Fastify.
> 
I would really like to see you do this, as the same can most likely be done with Fastify to achieve even faster speeds.
> > ```
> > * Failure to lint Prisma schema
> > ```
> 
> This is pedantic and yet again all down to code-style.
> 
I respect this, but it usually makes your code easier to read and maintain.
> > ```
> > * Useless env keys
> > ```
> 
> If you understand the code enough to be running it on your machine I wouldn't be worried about useless env keys, it's never going to cause an issue. Nor is ".env.example" even "code"
> 
I agree with this, but it's still somewhat useless.
> > ```
> > * Lack of code formatting and basic code practices
> > ```
> 
> What are "basic code practices?" The code looks perfectly formatted to me.
> 
> > Please in the future make use of ESLint to format your code, and pick one package manager, and make use of simple practices such as de-structuring, semicolons, and env validation. This code looks like it's written by a 12-year-old wannabe programmer.
> 
> Automatic semicolon insertion has been part of the ECMAScript spec for [as long as I can remember](https://www-archive.mozilla.org/js/language/E262-3.pdf), it is by no means a reason to use as a complaint about someone's code. Numerous of your favorite libraries may lack semicolons, such as [body-parser](https://github.com/expressjs/body-parser), hell, even **[fastify](https://github.com/fastify/fastify)** themselves don't use semicolons in their codebase!
> Environment key validation is useless and honestly a waste of time on something this small. There is an [ESLint config file](https://github.com/environment-dev/minio-image-proxy/blob/master/.eslintrc.js), obviously, you must have been too sleep-deprived to see it. Lastly, I see a use of object destructuring on the very first line of [index.js](https://github.com/environment-dev/minio-image-proxy/blob/master/index.js#L1)!
> 
Please take your time to read [this article](https://2ality.com/2011/05/semicolon-insertion.html). I think you might find it useful.  
> Obviously you were too "sleep-deprived" to be writing this issue and I think you should take your matters to another place.

Please take my stupid statement out of here.

**Comment by axisiscool** [comment]
> I'm almost certain that if these "issues" where present in aspect's code you would have completely ignored them

Aspect actually writes half decent code so I don't even have to correct them. All I'm saying is to follow simple practices to make your code look better. 

> There is an ESLint config file, obviously you must have been too sleep deprived to see it.

I'm aware that there is an ESLint config file, that's why I said **make use of ESLint**.

All of your other statements @Vetlix has already invalidated or they're just too stupid to come back to. Learn how to code please.

**Comment by axisiscool** [comment]
> Obviously you were too "sleep-deprived" to be writing this issue and I think you should take your matters to another place.

It was 6pm when I posted this issue. Although, I think I can still write better code at 5am than you can write any part of the day 😛

**Comment by aspectiscool** [comment]
> > I'm almost certain that if these "issues" where present in aspect's code you would have completely ignored them
> 
> Aspect actually writes half decent code so I don't even have to correct them. All I'm saying is to follow simple practices to make your code look better.
> 
> > There is an ESLint config file, obviously you must have been too sleep deprived to see it.
> 
> I'm aware that there is an ESLint config file, that's why I said **make use of ESLint**.
> 
> All of your other statements @Vetlix has already invalidated or they're just too stupid to come back to. Learn how to code please.

grrr grrrd my code best nooo GRRRR shuuuuuushbhg My code Best All grrrrrr sit down skid kid 👀👀👀🗣🗣🗣🗣

**Comment by environment-dev** [comment]
> > > ```
> > > * The use of yarn and npm
> > > ```
> > 
> > 
> > Nothing wrong with that, you shouldn't experience node_modules inconsistency unless the version is overwritten (which isn't possible in npm since at least 2014)
> 
> If you use both npm and yarn in a project, you will receive this warning:
> 
> ```prolog
> warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
> ```
> 
> I don't think it's put there for no reason.

I'd like to see a actually error caused by this.
> > > ```
> > > * Express usage, instead of fastify
> > > ```
> > 
> > 
> > This is pedantic and is all down to programmer preference. You can easily vertically scale express to perform better than Fastify.
> 
> I would really like to see you do this, as the same can most likely be done with Fastify to achieve even faster speeds.
>
I do not care about fastifys performance improvements. If you think I don't know fastify,I'll be more than happy to show that the project I'm working on uses fastify
> > > ```
> > > * Failure to lint Prisma schema
> > > ```
> > 
> > 
> > This is pedantic and yet again all down to code-style.
> 
> I respect this, but it usually makes your code easier to read and maintain.
>
I guess you have a point there.
> > > ```
> > > * Useless env keys
> > > ```
> > 
> > 
> > If you understand the code enough to be running it on your machine I wouldn't be worried about useless env keys, it's never going to cause an issue. Nor is ".env.example" even "code"
> 
> I agree with this, but it's still somewhat useless.
I don't think it should cause issues.
> > > ```
> > > * Lack of code formatting and basic code practices
> > > ```
> > 
> > 
> > What are "basic code practices?" The code looks perfectly formatted to me.
> > > Please in the future make use of ESLint to format your code, and pick one package manager, and make use of simple practices such as de-structuring, semicolons, and env validation. This code looks like it's written by a 12-year-old wannabe programmer.
> > 
> > 
> > Automatic semicolon insertion has been part of the ECMAScript spec for [as long as I can remember](https://www-archive.mozilla.org/js/language/E262-3.pdf), it is by no means a reason to use as a complaint about someone's code. Numerous of your favorite libraries may lack semicolons, such as [body-parser](https://github.com/expressjs/body-parser), hell, even **[fastify](https://github.com/fastify/fastify)** themselves don't use semicolons in their codebase!
> > Environment key validation is useless and honestly a waste of time on something this small. There is an [ESLint config file](https://github.com/environment-dev/minio-image-proxy/blob/master/.eslintrc.js), obviously, you must have been too sleep-deprived to see it. Lastly, I see a use of object destructuring on the very first line of [index.js](https://github.com/environment-dev/minio-image-proxy/blob/master/index.js#L1)!
> 
> Please take your time to read [this article](https://2ality.com/2011/05/semicolon-insertion.html). I think you might find it useful.
>
I'll read this when I'm at home.
> > Obviously you were too "sleep-deprived" to be writing this issue and I think you should take your matters to another place.
> 
> Please take my stupid statement out of here.

**Comment by environment-dev** [comment]
> > Obviously you were too "sleep-deprived" to be writing this issue and I think you should take your matters to another place.
> 
> It was 6pm when I posted this issue. Although, I think I can still write better code at 5am than you can write any part of the day 😛
> 

As strange as it sounds, sleep deprivation is largely independent of the time. And, I don't think you realize my code style intentionally omits semicolons.

**Comment by axisiscool** [comment]
> As strange as it sounds, sleep deprivation is largely independent of the time.

Correct, the statement was a hyperbole of sorts lol... Still stands though. Your code is unorganized, and can use improvement. I made this PR to try to help you make your code better. Please read the things @Vetlix sent, as they should help you improve your code.

**Comment by axisiscool** [comment]
As it's clear you're not going to heed any of my advice, or take constructive criticism, I'm going to close this.
